name: Deploy to Azure

on:
  push:
    branches:
      - main  # 배포할 브랜치 이름
    paths:
      - 'Front/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: actions/setup-node@v2
      with:
        flutter-version: '3.22.2'

    - name: Install dependencies
      run: flutter pub get

    - name: Build project
      run: flutter build web
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
      name: webapp
      path: build/web/

deploy:
  runs-on: ubuntu-latest
  needs: build
  environment: 'production'

  steps:
    -name: Download artifact from build job
     uses: actions/download-artifact@v2
     with:
      name: webapp

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'Inter-library-Loan'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: 'C:\inter_library_loan_new'
