name: Deploy to Azure

on:
  push:
    branches:
      - main  # 배포할 브랜치 이름
    paths:
      - 'Front/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Change to Front directory
        run: cd Front

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./Front

      - name: Build Flutter web
        run: flutter build web --target=lib/loginScreen.dart --no-tree-shake-icons
        working-directory: ./Front

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: ./Front/build/web/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: 'production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: flutter-web-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dankook2021'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: flutter-web-app