name: Deploy Spring Boot Backend to Azure

on:
  push:
    branches:
      - main
#    paths:
#      - 'back/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Grant execute permission for gradlew
        run: chmod +x ./Back/ill/gradlew

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: Back/ill

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: Back/ill/build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BEF4CDFA5D0A4F3EB1869E1106833671 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C7D741CD5EE742BD95163CA518A6DAEA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_826CA8C2F76E41C4A0C2F2879FC80426 }}


      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'inter-library'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'Back/ill/build/libs/*.jar'